#Anything that is optional which you are not using, just delete that line. You can also delete any of the '#comments'
 
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="All rights reserved" #mandatory https://choosealicense.com/
 
[[mods]] #mandatory
modId="birdieblocks" #mandatory
version="0.0.1" #mandatory
displayName="BirdieBlocks" #mandatory
#logoFile="logo.png" #optional #Uncomment once logo is created!!
authors="Robin // RedDevRedemption" #optional
description='''
Robin's Birdie Blocks Mod for 1.16.5!
Stairs n slabs galore!
''' #mandatory